### PR TITLE
Make boolean values accessible in react, e.g. "isWriteable" and "canMakeReadonly"

### PR DESCRIPTION
**Pull request by clrsustainas**
All other types than boolean is being returned to react, so I just added a type check for primitive booleans.

### CODE REVIEW

**Comment by whitedogg13** [comment]
It's awesome, thanks for contribution!

**Comment by ljsustainas** [comment]
closes #284

**Comment by clrsustainas** [comment]
> It's awesome, thanks for contribution!

Any time, thanks for a great nfc lib! 

Would it be possible to publish a patch with the merged changes to NPM?

**Comment by whitedogg13** [comment]
Hi @clrsustainas sure, v2.1.7 just published

**Comment by clrsustainas** [comment]
> Hi @clrsustainas sure, v2.1.7 just published

Much appreciated.
I used the wrong name in one of the functions though, so I've made a pull request here, that will fix it https://github.com/whitedogg13/react-native-nfc-manager/pull/288 .

**Pull request merged**
