### PR TITLE
Feature/mifareclassic write

### PR DESCRIPTION
**Pull request by poison**
Added write functionality

### CODE REVIEW

**Comment by whitedogg13** [comment]
@poison , I'd like to know your thought about version number for next release. 

Since we have both features and API changes, which version do you prefer?
1. Go from `0.7.0` to `1.0.0`
2. Go from `0.7.0` to `0.8.0`

Please let me know your preference, thanks!

**Comment by poison** [comment]
I'm a bit in doubt to be honest. On the one hand, I'd reserve going to 1.0.0 for a special major milestone (e.g.: being fully compatible with expo client, major iOS release, ...). But on the other hand, I think releasing 1.0.0 would be a strong signal to the community that the project is feature complete and stable, it would make it stand out more if you search for NFC in [npmjs](https://www.npmjs.com/search?q=nfc).

So I'd go for 1.0.0 and hope to grow the community, having more devices tested & bugs found etc. (to compare, phonegap-nfc is at version 1.0.3 and supports less features than this library)

Best,
Nicolas

**Comment by whitedogg13** [comment]
Got it, great opinion. Let's go for v1.0!

**Comment by whitedogg13** [comment]
@poison , 1.0.0 just published!

**Comment by poison** [comment]
If I find some time I'll draft up a changelog.md or something similar to keep track of the release notes.

**Comment by filippoitaliano** [comment]
@poison It would be awesome!

**Pull request merged**
