### PR TITLE
added basic mifareclassic support

### PR DESCRIPTION
**Pull request by poison**
Added basic support for MifareClassic cards. Any feedback / suggestions welcome to get this PR merged upstream.

Usage sample:
```
      NfcManager.requestTechnology(NfcTech.MifareClassic)
        .then(() => {
          NfcManager.mifareClassicAuthenticateA(2, String.fromCharCode(0xff, 0xff, 0xff, 0xff, 0xff, 0xff)).then(() => {
              NfcManager.getMifareClassicMessage(2)
                .then(data => {
                  console.log('Received MifareClassic data', data);
                  return;
                })
                .catch(err => {
                  console.log('Failed to read data: ', err);
                });
            })
            .catch(err => {
              console.log('Failed to authenticate: ', err);
            });
        })
        .catch(err => {
          console.log('Failed to tech request: ', err);
        });
```

### CODE REVIEW

**Comment by whitedogg13** [comment]
Hi @poison , thanks a lot!

**Comment by whitedogg13** [comment]
Hi @poison, really appreciated for the PR and I have merged it, but I have some questions regarding it (I don't have much experience play with `MifareClassic`, so please forgive me if the answer is obvious to you).  

I want to know why do we need to explicitly transform the byte array into a ASCII string in `getMifareClassicMessage`? is it a common use case for MifareClassic? 

Some background here: normally in a native-bridge library like this, we like to bring the native function as is to JS side, and let the JS side decide how to deal with it. However, of course we can do some further processing if there're some common use cases, that's why I'm asking this question. 

Thanks!

**Comment by whitedogg13** [comment]
@poison  thanks for responding!

**Comment by poison** [comment]
I changed it in #92 (checked how react-native-bluetooth-manager did it, they also pass arrays). Is this better for you?

Best,
Nicolas

**Pull request merged**
