### PR TITLE
added wifi utility for making wifi payload to write into nfc tag

### PR DESCRIPTION
**Pull request by deenMuhammad**
#### `ndef-wifi.js` file added 
This utility helps to create payload that is makes possible to create payload to write into nfc tag so that the nfc tag becomes wifiporter.
This utility is used just like `ndef-text` or `ndef-uri`.

##### function parameter: 
wifiRecord(credentials) gets `credentials` as parameter. `credentials` parameter should be object.
```json
credentials: {
    ssid:  String, 
    authType: String,
    networkKey: String
}
```
>authType is the type of authentication and can get two types of string parameters: `'WPA'` or `'NO'`. If the wifi is open then `'NO'`, if the wifi has `networkKey` then authKey should be equal to `'WPA'`(most common type of network authentication).

To Test this functionality use `example/AppNdefWifi.js`

TODO:  decoding wifi payload and making readable and processable object so that it can be parsed.

Please feel free to ask any question regarding this functionality.

### CODE REVIEW

**Comment by whitedogg13** [comment]
Hi @deenMuhammad sorry for the late response. This feature is awesome, and I do want to merge them into the library. However the commits in current PR seems to contain several unnecessary changes, can you make another one so it can be merged easier?

**Comment by deenMuhammad** [comment]
I got it!
I will be doing it as soon as possible and make one more PR

**Comment by jameslevine** [comment]
This is a great feature. Will the conflicts be resolved soon? Excited to see this become a reality.

**Comment by JGaudette** [comment]
Is there any update on adding this feature?

**Comment by deenMuhammad** [comment]
@JGaudette, sorry for late reply. I could not have time to edit the codes and push, but I think you did a great job. 
Thank you for making this available!
I appreciate it

**Comment by armsteadj1** [comment]
Is there any update on when this might be available

**Comment by whitedogg13** [comment]
Hi @armsteadj1 seems that @JGaudette has created #235, but some modification in `ndef-lib/ndef-utils.js` still need some check. It's a great feature, I will try to pick it up ASAP.

**Comment by armsteadj1** [comment]
Thanks @whitedogg13! That would be awesome. Let me know if there is any way i can be useful.

**Comment by whitedogg13** [comment]
Hi all, I have implemented an draft version for this feature in `v2.1.3`. Notice currently not all wifi credential fields are supported, only limited to `ssid`, `networkKey` and `authType` (default to `WPA2_PSK`). 

Example looks like this:
```javascript
import NfcManager, {NfcTech, Ndef} from 'react-native-nfc-manager';
...
let bytes = Ndef.encodeMessage([
  Ndef.wifiSimpleRecord({
    ssid: 'mywifi',
    networkKey: 'Abcdef123',
  }),
]);
await NfcManager.writeNdefMessage(bytes);
```

I will close this `PR` for now, thanks @JGaudette and @deenMuhammad for proposing the original version, and welcome for further enhancement!

Thanks!

**Pull request closed without merging**
