### PR TITLE
(Ios) add custom message & allow message to automatically close on scan

### PR DESCRIPTION
**Pull request by clickclickonsal**
This pull request adds 2 features. 
The first is the ability to add a custom message such as "Hold iPhone near the fire" shown below.
image
The second is the ability to have the popup automatically close when a tag is scanned & not have to click the "done" button to close the popup.

### CODE REVIEW

**Comment by whitedogg13** [comment]
Thanks!

**Comment by clickclickonsal** [comment]
No problem! Thank you for letting me contribute to the project! 😄

**Comment by clickclickonsal** [comment]
Could you publish this change to npm? Please 😄

**Comment by whitedogg13** [comment]
Just published & thanks for reminding~

**Pull request merged**
