### PR TITLE
Added sendFelicaCommandIOS

### PR DESCRIPTION
**Pull request by hataguchi**
Currently, it is not compatible with Felica on iOS, so we added command transmission with Felica

### CODE REVIEW

**Comment by whitedogg13** [comment]
It's awesome, thanks for the contribution!

**Comment by whitedogg13** [comment]
hi @hataguchi , I just found that my iPhone has issues scanning NFC tag when the `NFCPollingISO18092` is enabled, as described in #295 . I use iPhone 11, with iOS 13.4.1. Can you do a quick check about this? Or is there any further configurations required?

**Comment by hataguchi** [comment]
I described below in README.md, but this was a required item, not an option.

> In the ISO18092 system codes for NFC Tag Reader Session, all FeliCa system codes used for reading must be entered in advance. Wildcards cannot be used.

Ex
```
<key>com.apple.developer.nfc.readersession.felica.systemcodes</key>
<array>
    <string>0003</string>
</array>
```

**Comment by whitedogg13** [comment]
Hi @hataguchi roger that, thanks in advance! So in this case, I think we should limit `initWithPollingOption` only to directly requested ones rather that all, to avoid forcing client app to list unnecessary keys.

**Comment by hataguchi** [comment]
I think the change is a better refurbishment.

**Pull request merged**
