### PR TITLE
Wifi support for writing nfc

### PR DESCRIPTION
**Pull request by JGaudette**
This is a cleaned up version of the code that @deenMuhammad posted (1,2) previously.  I removed the unnecessary files and updates and successfully tested writing a WPA wifi credentials and regression tested by successfully writing a url.  Both were written on ios 13 and read using android.

1: https://github.com/whitedogg13/react-native-nfc-manager/issues/188
2: https://github.com/whitedogg13/react-native-nfc-manager/pull/200

### CODE REVIEW

**Comment by KBog** [comment]
Will this also add support to password protect an NFC tag?

**Comment by deenMuhammad** [comment]
@KBog, `Locking` and `Unlocking` NFC tag can be implemented differently for different tag type using already available functions built by @whitedogg13, such as `NfcManager.sendMifareCommandIOS`(for iOS) and `NfcManager.transceive`(for Android). 
I, personally used `NTAG215` NFC tag for my hardware and [this documentation](https://www.nxp.com/docs/en/data-sheet/NTAG213_215_216.pdf) was very helpful to understand how the tag and its locking is structured. If you do not understand this I am afraid you will not be able to achieve this functionality, given the fact that locking and unlocking is not built in this `react-native-nfc-manager` module.
Hope this will help!

**Comment by JGaudette** [comment]
@whitedogg13 is there anything else needed or can we get this merged?

Thanks in advance!

**Comment by whitedogg13** [comment]
@JGaudette This PR is awesome! I am just been too busy these days to response, and sorry for that. 

Just wonder, is the modification for `ndef-lib/ndef-util.js` required? Can we stick to the original version?

Thanks for your contribution!

**Comment by JGaudette** [comment]
@deenMuhammad would you be able to talk a bit about the changes to `ndef-lib/ndef-utils.js`?  I was unable to get the wifi writing to be recognized on devices without the change.

**Comment by whitedogg13** [comment]
Hi all, I have implemented an draft version for this feature in `v2.1.3`. Notice currently not all wifi credential fields are supported, only limited to `ssid`, `networkKey` and `authType` (default to `WPA2_PSK`). 

Example looks like this:
```javascript
import NfcManager, {NfcTech, Ndef} from 'react-native-nfc-manager';
...
let bytes = Ndef.encodeMessage([
  Ndef.wifiSimpleRecord({
    ssid: 'mywifi',
    networkKey: 'Abcdef123',
  }),
]);
await NfcManager.writeNdefMessage(bytes);
```

I will close this `PR` for now, thanks @JGaudette and @deenMuhammad for proposing the original version, and welcome for further enhancement!

Thanks!

**Pull request closed without merging**
